[theme]
primaryColor = "#10a37f"
backgroundColor = "#212121"
secondaryBackgroundColor = "#171717"
textColor = "#ececec"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
